version: '3.4'

services:

  raftweb:
    build:
      context: .
      dockerfile: RaftWeb1/Dockerfile
    ports:
      - "2000:80"
    networks:
      - raft_network

  raftapi:
    build:
      context: .
      dockerfile: RaftAPI/Dockerfile
    ports:
      - "2002:8080"
    environment:
      - NODES="http://raftapi2:8080,http://raftapi3:8080"
    networks:
      - raft_network

  raftapi2:
    build:
      context: .
      dockerfile: RaftAPI/Dockerfile
    ports:
      - "2003:8080"
    environment:
      - NODES="http://raftapi:8080,http://raftapi3:8080"
    networks:
      - raft_network

  raftapi3:
    build:
      context: .
      dockerfile: RaftAPI/Dockerfile
    ports:
      - "2004:8080"
    environment:
      - NODES="http://raftapi2:8080,http://raftapi:8080"
    networks:
      - raft_network

  gatewayapi:
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    ports:
      - "2010:8080"
    environment:
      - NODES="http://raftapi:8080,http://raftapi2:8080,http://raftapi3:8080"
    networks:
      - raft_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3103:3100"
    networks:
      - raft_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
    networks:
      - raft_network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-config.yaml:/etc/otel-collector/otel-config.yaml
    ports:
      - "4300:4317"
      - "55680:55680"
    networks:
      - raft_network

networks:
  raft_network:


volumes:
  grafana_data:

