receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tenant_id: "default"
    basic_auth:
      username: "admin"
      password: "admin"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
