name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# env: 
#   DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          include-prerelease: true


      - name: redeploy application
        run: |
            docker compose pull
            docker compose build --no-cache 
            docker compose down
            docker compose up -d
      
    #   - name: Format
    #     run: |
    #       cd web
    #       dotnet format 

      - name: Tests
        run: |
            cd RathTest
            dotnet test
