name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# env: 
#   DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push]
jobs:
  Test:
    runs-on: office2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
      - name: Run tests
        run: dotnet test RathTest


  deploy_to_server_4:
    runs-on: office4
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          include-prerelease: true


      - name: redeploy application
        run: |
            docker compose -f docker-compose2.yml pull
            docker compose -f docker-compose2.yml build --no-cache 
            docker compose -f docker-compose2.yml down
            docker compose -f docker-compose2.yml up -d
      

  deploy_to_server_2:
    runs-on: office2
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          include-prerelease: true


      - name: redeploy application
        run: |
            cd ops2
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml build --no-cache 
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d
